baseURL: "https://nizihan29.github.io/" 
title: Zihan Ni
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org
          weight: 6

params:
    description: "This website hosts Zihan Ni's research papers, data, curriculum vitae, and contact information."
    author: Zihan Ni
    googleAnalyticsID: "G-MHNMJDWTNX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zihan Ni
          subtitle: |
              Ciallo～(∠・ω< )⌒★ <br>
              Welcome! I am <b>Zihan Ni</b>, currently an intern at <i>IBM TRL</i> while pursuing my Master's degree at <i>Kyoto University</i>. 
              Beyond academia, I am an avid fan of anime and enjoy long walks. Recently, I’ve been deeply immersed in <i>Strinova</i>. <br><br>

              <b>Research Interests:</b>
              <ul style='list-style:none;padding:0;margin:0;'>
              <li>• Empathic AI</li>
              <li>• Psychoinformatics</li>
              </ul>
              <br>

              <b>Education:</b>
              <ul style='list-style:none;padding:0;margin:0;'>
              <li>• Apr. 2026 &ndash; Present: M.S. in Informatics, Kyoto University</li>
              <li>• Sep. 2021 &ndash; Jun. 2025: B.E. in Artificial Intelligence, Central South University</li>
              </ul>
          imageUrl: "avatar.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Blog
              url: https://en.wikipedia.org/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:nizihan29@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/zihan-ni-baa39636a/
        - name: GitHub
          url: https://github.com/nizihan29
        - name: X
          url: https://x.com/m1n645372

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zihan Ni"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
